parameters:
  - name: fluentVersion
    type: string
    default: v8
  - name: vrTestPackageName
    type: string
    default: '@fluentui/vr-tests'
  - name: vrTestPackagePath
    type: string
    default: 'apps/vr-tests'
  - name: shouldBuildstorybookaddon
    type: boolean
    default: false

steps:
  - script: |
      echo REASON
      echo $(Build.Reason)
      echo SOURCE BRANCH
      echo $(Build.SourceBranch)

      isPR=${{eq(variables['Build.Reason'], 'PullRequest')}}
      echo "Is PR build? $isPR"
      echo $isPR
    displayName: yarn (install packages)

  - task: Bash@3
    inputs:
      filePath: yarn-ci.sh
    displayName: yarn (install packages)

  - script: |
      isPR=${{eq(variables['Build.Reason'], 'PullRequest')}}
      packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests-react-components --pr=$isPR)
    displayName: Should

  - script: |
      yarn workspace ${{ parameters.vrTestPackageName }} convert
    displayName: Convert screener component to storywright

  - ${{ if eq(parameters.shouldBuildstorybookaddon, 'true') }}:
      - script: |
          yarn build --to @fluentui/react-storybook-addon
        displayName: Build react-storybook-addon

  - script: |
      yarn workspace ${{ parameters.vrTestPackageName }} screener:build
    displayName: Build VR tests components package

  - script: |
      yarn workspace ${{ parameters.vrTestPackageName }} test:component --verbose
    displayName: 'Run VR tests'

  - script: |
      mkdir -p screenshots
      cp -rf ${{ parameters.vrTestPackagePath }}/dist/screenshots/*.png screenshots/
    displayName: Collate Artifacts

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'screenshots'
      ArtifactName: 'vrscreenshot${{ parameters.fluentVersion }}'
      publishLocation: 'Container'
