pr:
  - master

# There's a separate pipeline for CI which also uses this file, but with a trigger override in the UI
# https://dev.azure.com/uifabric/fabricpublic/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=164&view=Tab_Triggers
trigger: none

variables:
  - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/')) }}:
      - name: sinceArg
        value: --since $(targetBranch)

  - template: .devops/templates/variables.yml

pool: '1ES-Host-Ubuntu'

jobs:
  - job: VisualRegressionTest_V9
    variables:
      pipelineId: '211'
      pipelineName: 'fluent-ui VRT Pipeline v9'

    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - bash: |
          postPolicy="true";
          response=$(curl --request POST 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'client_id=288a69b6-760d-4c1f-ad6d-0183b5e5740f' --data-urlencode 'client_secret='${VR_APPROVAL_CLIENT_SECRET} )
            parsedResponse=${response/*"access_token"/}
            token=${parsedResponse:3:${#parsedResponse}-5}
            curl --location --request POST 'https://vrt-fluentapp.azurewebsites.net/api/policyState' \
            --header 'Authorization: Bearer '"$token" \
            --header 'Content-Type: application/json' \
            --data-raw '	{
            "organization": "uifabric",
            "projectName": "fabricpublic",
            "prId": $(System.PullRequest.PullRequestNumber),
            "commitId": "$(Build.SourceVersion)",
              "generate":true,
              "blockingPipeline":{
              },
              "nonBlockingPipeline":{
                "$(pipelineId)": {
                  "pipelineStatus": "PENDING",
                  "pipelineName": "$(pipelineName)"
                }
              },
              "postPolicy": '${postPolicy}',
              "policyType": "OPTIONAL"
            }'
        displayName: 'Call policy State Api'
        env:
          VR_APPROVAL_CLIENT_SECRET: $(VR-APPROVAL-CLIENT-SECRET)

      - template: .devops/templates/runpublishvrscreenshot.yml
        parameters:
          fluentVersion: v9
          storyPackageName: '@fluentui/vr-tests-react-components'
          storyPackagePath: 'apps/vr-tests-react-components'
          shouldbuildstorybookaddon: true

  - job: VisualRegressionTest_V8
    variables:
      pipelineId: '212'
      pipelineName: 'fluent-ui VRT Pipeline v8'
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - bash: |
          postPolicy="true";
          response=$(curl --request POST 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'client_id=288a69b6-760d-4c1f-ad6d-0183b5e5740f' --data-urlencode 'client_secret='${VR_APPROVAL_CLIENT_SECRET} )
            parsedResponse=${response/*"access_token"/}
            token=${parsedResponse:3:${#parsedResponse}-5}
            curl --location --request POST 'https://vrt-fluentapp.azurewebsites.net/api/policyState' \
            --header 'Authorization: Bearer '"$token" \
            --header 'Content-Type: application/json' \
            --data-raw '	{
            "organization": "uifabric",
            "projectName": "fabricpublic",
            "prId": $(System.PullRequest.PullRequestNumber),
            "commitId": "$(Build.SourceVersion)",
              "generate":true,
              "blockingPipeline":{
              },
              "nonBlockingPipeline":{
                "$(pipelineId)": {
                  "pipelineStatus": "PENDING",
                  "pipelineName": "$(pipelineName)"
                }
              },
              "postPolicy": '${postPolicy}',
              "policyType": "OPTIONAL"
            }'
        displayName: 'Call policy State Api'
        env:
          VR_APPROVAL_CLIENT_SECRET: $(VR-APPROVAL-CLIENT-SECRET)

      - template: .devops/templates/runpublishvrscreenshot.yml
        parameters:
          fluentVersion: v8
          storyPackageName: '@fluentui/vr-tests'
          storyPackagePath: 'apps/vr-tests'
          shouldbuildstorybookaddon: false
