pr:
  - master

# There's a separate pipeline for CI which also uses this file, but with a trigger override in the UI
# https://dev.azure.com/uifabric/fabricpublic/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=164&view=Tab_Triggers
trigger: none

variables:
  - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/')) }}:
      - name: sinceArg
        value: --since $(targetBranch)

  - template: .devops/templates/variables.yml

pool: '1ES-Host-Ubuntu'

jobs:
  - job: TestVRTool
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn (install packages)

      - script: |
          yarn workspace @fluentui/vr-tests-react-components screener:build
        displayName: Build vr tests components package

      - script: |
          yarn lage test:component --verbose
        displayName: 'Run VR tests'

      - script: |
          mkdir -p screenshots
          cp -rf apps/vr-tests-react-components/dist/screenshots/*.png screenshots/
          cd screenshots
          for file in *"\""*; do
            echo $file
            mv -- "$file" "${file//\"/}"
          done

          for file in *"<"*; do
            echo $file
            mv -- "$file" "${file//</ }"
          done

          for file in *">"*; do
            echo $file
            mv -- "$file" "${file//>/ }"
          done
        displayName: Collate Artifacts

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'screenshots'
          ArtifactName: 'vrscreenshot'
          publishLocation: 'Container'

      - bash: cd packages/screenshotdiff && yarn build
        displayName: 'Build'

      - bash: node packages/screenshotdiff/lib/index.js test --clientType "fluentui" --buildId 12345
        displayName: 'Run fluentui-screenshotdiff'
        env:
          API_URL: $(System.CollectionUri)
          API_TOKEN: $(TEST_PAT)
          API_REPOSITORY: $(Build.Repository.Name)
          API_PROJECT: $(System.TeamProject)
          GITHUB_API_TOKEN: $(GITHUB_TEST_PAT)
          STORAGE_ACCOUNT_FLUENTUI: $(STORAGE-ACCOUNT-FLUENTUI)
          STORAGE_KEY_FLUENTUI: $(STORAGE-KEY-BLOB-FLUENTUI)

      - template: .devops/templates/cleanup.yml
